# Generated by Django 4.0.5 on 2022-06-18 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recursos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animais',
            fields=[
                ('criados', models.DateField(auto_now_add=True, verbose_name='Criação')),
                ('modificado', models.DateField(auto_now=True, verbose_name='Atualização')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo?')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comeu', models.BooleanField(default=False)),
                ('bebeu', models.BooleanField(default=False)),
                ('saiu', models.BooleanField(default=False)),
                ('peso', models.CharField(max_length=100, verbose_name='Recurso')),
                ('saude', models.TextField(max_length=200, verbose_name='Descricao')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animais',
            },
        ),
    ]
