# Generated by Django 4.0.5 on 2022-06-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_animais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animais',
            name='peso',
            field=models.CharField(max_length=100, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='animais',
            name='saude',
            field=models.TextField(max_length=200, verbose_name='saude'),
        ),
    ]
